### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yk-pku** [LingyiHongfd/LVOS-api#1]
During inference in the valid split, the RuntimeError occurred in line 105 of video_reader.py, i.e, the function of resize_mask
"RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 720, 1280]"

**Comment by LingyiHongfd** [comment]
Hi, can you provide more information about your problem? If you can provide more details about the model, LVOS version, and so on, maybe I can help you better.

Besides, we are organising the 6th Large-scale Video Object Segmentation (LSVOS) challenge in conjunction with ECCV 2024. Welcome to attend! For more details about the challenge, please refer to https://lsvos.github.io/

Best regards,
Lingyi

**Comment by yk-pku** [comment]
I am using the STCN model. I just found the problem may be caused by the 'msk' being empty. 
The current valid video is d83wYdy0, the reference frames in Annotations_convert are 00000001.png and 00001156.png. However, the 00000001.png contains no object.

**Comment by yk-pku** [comment]
I guess this is because there is a bug in tools/convert_mask_for_eval.py, as 'objs' needs to be initialized by [0], rather than []. 0 is for background, in the current version, the first frame will be treated as the reference frame regardless of whether there is an object or not.

**Comment by yk-pku** [comment]
By the way, thanks for organising the 6th Large-scale Video Object Segmentation (LSVOS) challenge, I will look for that latter~

**Comment by LingyiHongfd** [comment]
Because it's been a bit long and I haven't done vos for a long time, I can't remember a lot of details in the code. I'm very sorry. I think you can refer to [Cutie](https://github.com/hkchengrex/Cutie/blob/main/docs/EVALUATION.md) for some details about the mask pre-process. The code of dataset in Cutie is similar to that in STCN. I think it can help you.

Best regards,
Lingyi

**Comment by yk-pku** [comment]
I think it should be the problem I just mentioned, because after that problem being fixed, the inference procedure can be completed.

**Comment by LingyiHongfd** [comment]
Thanks a lot. I will fix this bug within the next few days.
